sudo: required
language: generic
services:
- docker
env:
  matrix:
    - HHVM_VERSION=4.41.0
    - HHVM_VERSION=4.42.0
    - HHVM_VERSION=4.43.0
    - HHVM_VERSION=4.44.0
    - HHVM_VERSION=4.45.0
    - HHVM_VERSION=4.46.0
    - HHVM_VERSION=4.47.0
    - HHVM_VERSION=4.48.0
    - HHVM_VERSION=4.49.0
    - HHVM_VERSION=4.50.0
    - HHVM_VERSION=4.51.0
    - HHVM_VERSION=4.52.1
    - HHVM_VERSION=4.53.0
    - HHVM_VERSION=latest
install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
notifications:
  slack:
    secure: 1DYmSh1d2svT1hEnSGibfwsF12zagvKs4MH9A8knZacH37MGw3Y2RgV34ZWWxjXb3/9nMUlDoscYhWNDMWyb2ncGJeBBSF2sB7EzSMAzu0EpWSjKI97WqF/pEyGmSdVjZgVoWeXWHx5qWchCXPLgJX2/jcNyibBHjhRefsFRudnLBjUjVI1tVUCORRuGAjsTsTMfH7aa803Uu6E3oJHrUMLLw4c5CWXg56x2sDJ94BxhImPMj4HAiIzW0mXoDPRLD1FHQbB+IFWBja2kbNmv5B/ewiByCrYSbkI2WR1t3aGbrzdGIY2y5hQrWkgYJSpU4J1GRfJvw/wOwSD+PKUft+3MQ1hrst+Rj6AgDAyNuB85M+mi2IHM7h4lITPEIKlnX8umprvBB9fBqTMIgiMk5BkIisEzmuzJ1GlgRa0eeJ06aUJiDGTK8aVLNztjguIykXMCqxJqhBcQlqvlIv6kzvY8+EkBC8T5tV11sfVckgvzNo7Re4OZd4TtaY2Bvr6suBnWrOZLewQfC0Mm7ESXnRQDQTyS4w5ZKnKyau29TQADOCAH2kwtZQ3FfZrFZPkuFV2avcGU4FtIRnWgbw7ZAkcW6FWmMLCTuZmxweN+7S9P0rWe+l3Ih1tN9EKy11Rzz7W1uA6SsRdo3axLmSEW7XQcADDUdN0/ApwQcgHe6sI=
